from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from main import views

urlpatterns = [
    path('Speed0', views.Speed0, name="Speed0"),
    path('Speed1', views.Speed1, name="Speed1"),
    path('Speed2', views.Speed2, name="Speed2"),
    path('Speed3', views.Speed3, name="Speed3"),
    path('Speed4', views.Speed4, name="Speed4"),
    path('Speed5', views.Speed5, name="Speed5"),
    path('datastring', views.datastring, name="datastring"),
    path('hepaLifeReset', views.hepaLifeReset, name="hepaLifeReset"),
    path('uvOn', views.uvOn, name="uvOn"),
    path('uvOff', views.uvOff, name="uvOff"),
    path('get_achsetup_json', views.get_achsetup_json, name="get_achsetup_json"),
    path('get_achcalibration_json', views.get_achcalibration_json, name="get_achcalibration_json"),
    path('update_achcalibration', views.update_achcalibration, name="update_achcalibration"),
    path('update_achsetup', views.update_achsetup, name="update_achsetup"),
    path('set_press_average', csrf_exempt(views.set_press_average), name="set_press_average"),
    path('set_flow_average', csrf_exempt(views.set_flow_average), name="set_flow_average"),
    path('touch_alarm', views.touch_alarm, name="touch_alarm"),
    path('alarm_on', views.alarm_on, name="alarm_on"),
    path('alarm_off', views.alarm_off, name="alarm_off"),
    path('log_sensors', views.log_sensors, name="log_sensors"),
    path('verify_password', views.verify_password, name="verify_password"),
    path('store_data', views.store_data, name="store_data"),
    path('change_log_interval', views.change_log_interval, name="change_log_interval"),
    path('change_display_type', views.change_display_type, name="change_display_type"),
    path('features/json', views.get_features_json, name="get_features_json"),
    path('sound/json', views.get_sound_json, name="get_sound_json"),
    path('update_features', views.update_features, name="update_features"),
    path('update_sound', views.update_sound, name="update_sound"), 
    path('set_password_state', views.set_password_state, name="set_password_state"), 
    path('display/json', views.get_display_json, name="get_display_json"),
    path('update_display', views.update_display, name="update_display"),  
    path('set_clock', views.set_clock, name="set_clock"),
    path('get_sensors/json', views.get_sensors, name="get_sensors"),
    path('profile_json/<int:room>/<int:profile>/json', views.get_profile_json, 
        name="get_profile_json"),
    path('toggle_room/<int:room>/json', views.toggle_room, name="toggle_room"),
    path('toggle_profile/<int:profile_index>/json', views.toggle_profile, name="toggle_profile"),
    path('network/json', views.get_network_json, name="get_network_json"),
    path('update_profile', views.update_profile, name="update_profile"),
    path('update_network', views.update_network, name="update_network"),
    path('update_sensor', views.update_sensor, name="update_sensor"),
    path('view_data', views.view_data, name="view_data"),
    path('view_password', views.view_password, name="view_password"),
    path('reset_password', views.reset_password, name="reset_password"),
    path('erase_data', views.erase_data, name="erase_data"),
    path('comm/json', views.get_comm_json, name="get_comm_json"),
    path('update_comm', views.update_comm, name="update_comm"),
]
