# Generated by Django 2.2.6 on 2019-10-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempSensorConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_active', models.BooleanField(default=False)),
                ('low_warning', models.FloatField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
