# Generated by Django 2.2.6 on 2019-10-03 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191003_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=None)),
                ('temp_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TempSensorConfig')),
            ],
        ),
    ]
