# Generated by Django 2.2.6 on 2019-10-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_configuration_log_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='room',
            new_name='active_room',
        ),
        migrations.AlterField(
            model_name='humsensorconfig',
            name='high_alarm',
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name='humsensorconfig',
            name='high_warning',
            field=models.FloatField(default=24.0),
        ),
        migrations.AlterField(
            model_name='humsensorconfig',
            name='low_alarm',
            field=models.FloatField(default=19.0),
        ),
        migrations.AlterField(
            model_name='humsensorconfig',
            name='low_warning',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='tempsensorconfig',
            name='high_alarm',
            field=models.FloatField(default=30.0),
        ),
        migrations.AlterField(
            model_name='tempsensorconfig',
            name='high_warning',
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name='tempsensorconfig',
            name='low_alarm',
            field=models.FloatField(default=15.0),
        ),
        migrations.AlterField(
            model_name='tempsensorconfig',
            name='low_warning',
            field=models.FloatField(default=20.0),
        ),
    ]
