# Generated by Django 2.2.6 on 2019-10-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='log_interval',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
