# Generated by Django 2.2.6 on 2019-10-04 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20191004_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempSensorConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_active', models.BooleanField(default=False)),
                ('profile', models.PositiveSmallIntegerField(default=1)),
                ('low_alarm', models.FloatField(default=15.0)),
                ('low_warning', models.FloatField(default=20.0)),
                ('high_alarm', models.FloatField(default=30.0)),
                ('high_warning', models.FloatField(default=25.0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HumSensorConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_active', models.BooleanField(default=False)),
                ('profile', models.PositiveSmallIntegerField(default=1)),
                ('low_alarm', models.FloatField(default=19.0)),
                ('low_warning', models.FloatField(default=20.0)),
                ('high_alarm', models.FloatField(default=25.0)),
                ('high_warning', models.FloatField(default=24.0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
