# Generated by Django 2.2.6 on 2019-10-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_humsensorconfig_tempsensorconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='active_profile',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
