# Generated by Django 2.2.6 on 2019-10-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_room_type_positive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
