# Generated by Django 2.2.6 on 2019-10-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_configuration_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='ip',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
