# Generated by Django 2.2.6 on 2001-01-01 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20010101_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display',
            old_name='sceen_lock',
            new_name='screen_lock',
        ),
    ]
