# Generated by Django 2.2.6 on 2019-10-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20191007_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='password',
            field=models.CharField(blank=True, default='master', max_length=30, null=True),
        ),
    ]
