# Generated by Django 2.2.6 on 2019-10-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20191007_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(blank=True, default='master', max_length=30, null=True),
        ),
    ]
