# Generated by Django 2.2.6 on 2019-10-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_configuration_lock_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='lock_counter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
