# Generated by Django 2.2.6 on 2019-10-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20191008_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='do_lock',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='lock_counter',
        ),
        migrations.AlterField(
            model_name='room',
            name='color',
            field=models.IntegerField(choices=[(1, 'Gray'), (2, 'DarkGray'), (3, 'White'), (4, 'Blue'), (5, 'Navy'), (6, 'DarkGreen'), (7, 'Green'), (8, 'Yellow'), (9, 'Orange'), (10, 'Red')], default=1),
        ),
    ]
