# Generated by Django 2.2.6 on 2019-10-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_achsensorconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowsensorconfig',
            name='metric',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AchSensorConfig',
        ),
    ]
