# Generated by Django 3.0 on 2019-12-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20191108_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_index', models.PositiveSmallIntegerField(default=None)),
                ('profile_index', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(default=None, max_length=30)),
                ('color', models.IntegerField(choices=[(1, 'Gray'), (2, 'DarkGray'), (3, 'White'), (4, 'Blue'), (5, 'Navy'), (6, 'DarkGreen'), (7, 'Green'), (8, 'Yellow'), (9, 'Orange'), (10, 'Red')], default=3)),
            ],
        ),
    ]
