# Generated by Django 3.0 on 2019-12-06 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='active_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
