# Generated by Django 3.0 on 2019-12-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='active_room',
        ),
        migrations.RemoveField(
            model_name='flowsensorconfig',
            name='room',
        ),
        migrations.RemoveField(
            model_name='humsensorconfig',
            name='room',
        ),
        migrations.RemoveField(
            model_name='partsensorconfig',
            name='room',
        ),
        migrations.RemoveField(
            model_name='presssensorconfig',
            name='room',
        ),
        migrations.RemoveField(
            model_name='tempsensorconfig',
            name='room',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='room',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
