# Generated by Django 3.0 on 2019-12-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20191210_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowsensorconfig',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='humsensorconfig',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='partsensorconfig',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='presssensorconfig',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='tempsensorconfig',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
