# Generated by Django 3.0 on 2019-12-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20191210_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowsensorconfig',
            name='high_alarm',
            field=models.PositiveSmallIntegerField(default=1100),
        ),
        migrations.AlterField(
            model_name='flowsensorconfig',
            name='high_warning',
            field=models.PositiveSmallIntegerField(default=1050),
        ),
        migrations.AlterField(
            model_name='flowsensorconfig',
            name='low_warning',
            field=models.PositiveSmallIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='humsensorconfig',
            name='high_alarm',
            field=models.FloatField(default=60.0),
        ),
        migrations.AlterField(
            model_name='humsensorconfig',
            name='high_warning',
            field=models.FloatField(default=55.0),
        ),
        migrations.AlterField(
            model_name='partsensorconfig',
            name='high_alarm',
            field=models.PositiveSmallIntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='partsensorconfig',
            name='high_warning',
            field=models.PositiveSmallIntegerField(default=300),
        ),
    ]
