# Generated by Django 3.0 on 2019-12-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20191210_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='press_avg',
            field=models.FloatField(default=0.0),
        ),
    ]
