# Generated by Django 3.0 on 2019-12-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_configuration_press_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='press_avg',
        ),
        migrations.AddField(
            model_name='presssensorconfig',
            name='average',
            field=models.FloatField(default=0.0),
        ),
    ]
