# Generated by Django 3.0 on 2019-12-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_auto_20191217_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowsensorconfig',
            name='diameter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flowsensorconfig',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flowsensorconfig',
            name='square',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flowsensorconfig',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flowsensorconfig',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
