# Generated by Django 3.0 on 2019-12-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_auto_20191217_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowsensorconfig',
            name='volume',
            field=models.FloatField(default=28.0),
        ),
    ]
