# Generated by Django 2.2.6 on 2020-12-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_auto_20191218_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacnet_status', models.BooleanField(default=False)),
                ('baudrate', models.CharField(blank=True, default='None', max_length=30, null=True)),
                ('mac_adress', models.CharField(blank=True, default='None', max_length=30, null=True)),
                ('object_instance', models.CharField(blank=True, default='None', max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=models.IntegerField(choices=[(1, 'Grey'), (2, 'DarkGrey'), (3, 'Blue'), (4, 'Navy'), (5, 'DarkGreen'), (6, 'Green'), (7, 'Yellow'), (8, 'Orange'), (9, 'Red')], default=4),
        ),
        migrations.AddField(
            model_name='configuration',
            name='comm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Comm'),
        ),
    ]
