# Generated by Django 2.2.6 on 2019-10-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=None)),
                ('humidity', models.FloatField(default=None)),
                ('pressure', models.FloatField(default=None)),
                ('airflow', models.PositiveSmallIntegerField(default=None)),
                ('analog', models.PositiveSmallIntegerField(default=None)),
                ('particles', models.PositiveSmallIntegerField(default=None)),
                ('room_1', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
