# Generated by Django 2.2.6 on 2019-10-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tempsensorconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsensorconfig',
            name='high_alarm',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='tempsensorconfig',
            name='high_warning',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='tempsensorconfig',
            name='low_alarm',
            field=models.FloatField(default=None),
        ),
    ]
