# Generated by Django 2.2.6 on 2019-10-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumSensorConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_active', models.BooleanField(default=False)),
                ('low_alarm', models.FloatField(default=None)),
                ('low_warning', models.FloatField(default=None)),
                ('high_alarm', models.FloatField(default=None)),
                ('high_warning', models.FloatField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
