# Generated by Django 2.2.6 on 2019-10-04 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=None)),
                ('name', models.CharField(default=None, max_length=30)),
                ('color', models.IntegerField(choices=[(1, 'Green'), (2, 'Blue'), (3, 'Red'), (4, 'Yellow')], default=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
        ),
    ]
