# Generated by Django 2.2.6 on 2019-10-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='log_interval',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
