# Generated by Django 2.2.6 on 2019-10-04 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191004_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
