# Generated by Django 2.2.6 on 2019-10-04 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191004_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=None)),
                ('hum_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HumSensorConfig')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Room')),
                ('temp_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TempSensorConfig')),
            ],
        ),
    ]
