# Generated by Django 2.2.6 on 2019-10-04 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20191004_0048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HumSensorConfig',
        ),
        migrations.DeleteModel(
            name='TempSensorConfig',
        ),
    ]
