# Generated by Django 2.2.6 on 2019-10-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_flowsensorconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempsensorconfig',
            name='alarm_active',
        ),
        migrations.AddField(
            model_name='flowsensorconfig',
            name='delay',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='humsensorconfig',
            name='delay',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
