# Generated by Django 2.2.6 on 2019-10-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='log_seconds',
            field=models.PositiveSmallIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='log_interval',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='color',
            field=models.IntegerField(choices=[(1, 'Black'), (2, 'Gray'), (3, 'DarkGray'), (4, 'LightGray'), (5, 'White'), (6, 'Aquamarine'), (7, 'Blue'), (8, 'Navy'), (9, 'Purple'), (10, 'DeepPink'), (11, 'Violet'), (12, 'Pink'), (13, 'DarkGreen'), (14, 'Green'), (15, 'YellowGreen'), (16, 'Yellow'), (17, 'Orange'), (18, 'Red'), (19, 'Brown'), (20, 'BurlyWood'), (21, 'Beige')], default=1),
        ),
    ]
