# Generated by Django 2.2.6 on 2019-10-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20191006_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='log_seconds',
        ),
    ]
