# Generated by Django 2.2.6 on 2019-10-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_configuration_log_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='display_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
