# Generated by Django 2.2.6 on 2019-10-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20191007_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
