# Generated by Django 2.2.6 on 2019-10-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20191007_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
