# Generated by Django 2.2.6 on 2019-10-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_network_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.BooleanField(default=True)),
                ('humidity', models.BooleanField(default=True)),
                ('pressure', models.BooleanField(default=True)),
                ('airflow', models.BooleanField(default=True)),
                ('analog', models.BooleanField(default=True)),
                ('particles', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='hum_active',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='temp_active',
        ),
        migrations.AddField(
            model_name='configuration',
            name='features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Features'),
        ),
    ]
