# Generated by Django 2.2.6 on 2019-10-07 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20010101_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='configuration',
            name='password',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Password'),
        ),
    ]
