# Generated by Django 2.2.6 on 2019-10-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_configuration_do_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='lock_counter',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
