# Generated by Django 2.2.6 on 2019-10-13 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20191010_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchSensorConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.PositiveSmallIntegerField(default=1)),
                ('metric', models.BooleanField(default=True)),
                ('alarm_active', models.BooleanField(default=False)),
                ('delay', models.PositiveSmallIntegerField(default=0)),
                ('low_alarm', models.FloatField(default=40.0)),
                ('low_warning', models.FloatField(default=45.0)),
                ('high_alarm', models.FloatField(default=55.0)),
                ('high_warning', models.FloatField(default=60.0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
