# Generated by Django 2.2.6 on 2019-10-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_flowsensorconfig_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='presssensorconfig',
            name='high_alarm_neg',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='presssensorconfig',
            name='high_warning_neg',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='presssensorconfig',
            name='low_alarm_neg',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='presssensorconfig',
            name='low_warning_neg',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='presssensorconfig',
            name='negative_room',
            field=models.BooleanField(default=False),
        ),
    ]
