# Generated by Django 2.2.6 on 2019-10-14 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20191014_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartSensorConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.PositiveSmallIntegerField(default=1)),
                ('alarm_active', models.BooleanField(default=False)),
                ('delay', models.PositiveSmallIntegerField(default=0)),
                ('low_alarm', models.PositiveSmallIntegerField(default=100)),
                ('low_warning', models.PositiveSmallIntegerField(default=200)),
                ('high_alarm', models.PositiveSmallIntegerField(default=300)),
                ('high_warning', models.PositiveSmallIntegerField(default=400)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
