# Generated by Django 2.2.6 on 2019-10-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20191031_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowsensorconfig',
            name='high_alarm',
            field=models.PositiveSmallIntegerField(default=1050),
        ),
        migrations.AlterField(
            model_name='flowsensorconfig',
            name='high_warning',
            field=models.PositiveSmallIntegerField(default=1100),
        ),
        migrations.AlterField(
            model_name='flowsensorconfig',
            name='low_alarm',
            field=models.PositiveSmallIntegerField(default=950),
        ),
        migrations.AlterField(
            model_name='flowsensorconfig',
            name='low_warning',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
