# Generated by Django 2.2.6 on 2020-02-07 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20191108_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_index', models.PositiveSmallIntegerField(default=None)),
                ('profile_index', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(default=None, max_length=30)),
                ('color', models.IntegerField(choices=[(1, 'Gray'), (2, 'DarkGray'), (3, 'White'), (4, 'Blue'), (5, 'Navy'), (6, 'DarkGreen'), (7, 'Green'), (8, 'Yellow'), (9, 'Orange'), (10, 'Red')], default=4)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='active_room',
        ),
        migrations.RemoveField(
            model_name='flowsensorconfig',
            name='room',
        ),
        migrations.RemoveField(
            model_name='humsensorconfig',
            name='room',
        ),
        migrations.RemoveField(
            model_name='partsensorconfig',
            name='room',
        ),
        migrations.RemoveField(
            model_name='presssensorconfig',
            name='room',
        ),
        migrations.RemoveField(
            model_name='tempsensorconfig',
            name='room',
        ),
        migrations.AddField(
            model_name='flowsensorconfig',
            name='average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flowsensorconfig',
            name='diameter',
            field=models.FloatField(default=203.0),
        ),
        migrations.AddField(
            model_name='flowsensorconfig',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flowsensorconfig',
            name='k_factor',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='flowsensorconfig',
            name='square',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flowsensorconfig',
            name='volume',
            field=models.FloatField(default=28.0),
        ),
        migrations.AddField(
            model_name='flowsensorconfig',
            name='width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='presssensorconfig',
            name='average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='flowsensorconfig',
            name='high_alarm',
            field=models.PositiveSmallIntegerField(default=1100),
        ),
        migrations.AlterField(
            model_name='flowsensorconfig',
            name='high_warning',
            field=models.PositiveSmallIntegerField(default=1050),
        ),
        migrations.AlterField(
            model_name='flowsensorconfig',
            name='low_warning',
            field=models.PositiveSmallIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='flowsensorconfig',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='humsensorconfig',
            name='high_alarm',
            field=models.FloatField(default=60.0),
        ),
        migrations.AlterField(
            model_name='humsensorconfig',
            name='high_warning',
            field=models.FloatField(default=55.0),
        ),
        migrations.AlterField(
            model_name='humsensorconfig',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='room',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='partsensorconfig',
            name='high_alarm',
            field=models.PositiveSmallIntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='partsensorconfig',
            name='high_warning',
            field=models.PositiveSmallIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='partsensorconfig',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='presssensorconfig',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='tempsensorconfig',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='configuration',
            name='active_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
